on: workflow_dispatch

jobs:
  generate_cursor_theme_job:
    runs-on: ubuntu-latest
    name: Export latest cursor theme and assets from Figma file
    env:
      EXPORT_DIRECTORY: export
      OUTPUT_DIRECTORY: assets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Export
        id: figma_export
        uses: phisch/cursor-theme-builder/action/export@v1.0
        with:
          access_token: ${{ secrets.FIGMA_ACCESS_TOKEN }}
          file_key: ${{ secrets.FIGMA_FILE_KEY }}
          theme_name: Your Cursor Theme Name
          theme_author: Your Name
          theme_comment: Describe your cursor theme here.
          output_directory: ${{ env.EXPORT_DIRECTORY }}

      - name: Update assets
        run: |
          rm -rf $OUTPUT_DIRECTORY
          mv $EXPORT_DIRECTORY $OUTPUT_DIRECTORY

      - name: Commit and push updated assets
        uses: EndBug/add-and-commit@v9
        with:
          add: ${{ env.OUTPUT_DIRECTORY }}
          default_author: github_actor
          message: 'exported assets from figma file ${{ secrets.FIGMA_FILE_KEY }} version ${{ steps.figma_export.outputs.version }}'
